### ISSUE TITLE
Can't find on Pluralsight

### ISSUE THREAD

**Issue by slimshader** [la-yumba/functional-unit-testing-dot-net#1]
Hey, just stumbled upon this repo while looking the code for your great "Logic vs. side effects: functional goodness you don't hear about" on YouTube (is it still available somewhere?) but I discovered this now I am not able to find the course on Pluralsight.

**Comment by la-yumba** [comment]
Hi, the talk was given at NDC (not on Pluralsight) and is available [on youtube](https://www.youtube.com/watch?v=wJq86IXkFdQ).
Thank you for appreciative comments

**Comment by la-yumba** [comment]
Sorry; this repo here was created as a draft for a course on Pluralsight; however, in the end we were not able to establish a working relation with Pluralsight, so I dropped the project.

**Comment by slimshader** [comment]
> Hi, the talk was given at NDC (not on Pluralsight) and is available [on youtube](https://www.youtube.com/watch?v=wJq86IXkFdQ).
> Thank you for appreciative comments

Yeah, I got here from YouTube (even mentioned that ;)), was looking for code for that video and stumbled upon this repo which mentioned Pluralsight course, sorry if I wan't clear. Anyways I found [the correct one](https://github.com/la-yumba/ndc-sydney-2017) and very sorry to hear about Ps course being canceled. Love your book too, hope for 2nd edition soon ;)
